version: '3.1'

services:

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 80
    volumes:
      - /home/fuchs/storage/nextcloud/html:/var/www/html
      - /home/fuchs/storage/nextcloud/custom_apps:/var/www/html/custom_apps
      - /home/fuchs/storage/nextcloud/config:/var/www/html/config
      - /home/fuchs/storage/nextcloud/data:/var/www/html/data
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: WOLF_FUCHS_20052018_db_nc
      MYSQL_DATABASE: db_nextcloud
      MYSQL_USER: nextcloud
      VIRTUAL_HOST: derfuchs.ddns.net
      LETSENCRYPT_HOST: derfuchs.ddns.net
      LETSENCRYPT_EMAIL: thilowendt@yahoo.de
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: WOLF_FUCHS_20052018_nc
      NEXTCLOUD_TRUSTED_DOMAINS: derfuchs.ddns.net
    networks:
      - frontend
      - backend
      - proxy-tier

networks:
  frontend:
    external:
      name: frontend
  backend:
    external:
      name: backend
  proxy-tier:
    external:
      name: proxy-tier
